### PR TITLE
Bug fix: Optimizing branch lengths in NNI Engine via GP

### LINKED ISSUE #483: Bug: GP Branch lengths are not being updated from default branch length during NNI search.

### PR DESCRIPTION
**Pull request by davidrich27**
## Description

- Fixes bug that caused NNI search to not optimize new branches when using a GP evaluation engine.
- Adds pybito function that gives NNIEngine read access to its evaluation engine's branch lengths (if using a parsimony engine that does not have branch lengths, throws error.)
- Minor fixes to fully_connect and git_commit functions.

Closes #483 

## Tests

N/A

## Checklist:

* [x] Code follows our detailed [contribution guidelines](CONTRIBUTING.md)
* [x] `clang-format` has been run
* [x] TODOs have been eliminated from the code
* [x] Comments are up to date, document intent, and there are no commented-out code blocks
* [ ] Issue branch has been squashed and rebased on main branch
* [ ] GitHub CI build on PR branch completed successfully

### CODE REVIEW

File: src/nni_evaluation_engine.cpp [hunk 1]
```diff
@@ -132,16 +130,18 @@ void NNIEvalEngineViaGP::UpdateEngineAfterModifyingDAG(
...
-      std::ignore = pre_nni;
-      NNIBranchLengthOptimization(nni, new_edge_ids);
-    }
-    GetGPEngine().ProcessOperations(GetDAG().PopulatePLVs());
+  if (optimize_new_edges_) {
+    // for (const auto &[pre_nni, nni] : pre_nni_to_nni) {
+    //   std::ignore = pre_nni;
+    //   NNIBranchLengthOptimization(nni, new_edge_ids);
+    // }
+    // GetGPEngine().ProcessOperations(GetDAG().PopulatePLVs());
```
Comment (chrisjenningsshaffer) [inline src/nni_evaluation_engine.cpp:138]: Is it safe to now remove the commented code.

File: src/nni_evaluation_engine.cpp [hunk 2]
```diff
@@ -132,16 +130,18 @@ void NNIEvalEngineViaGP::UpdateEngineAfterModifyingDAG(
...
+    BranchLengthOptimization();
   }
 
   GetGPEngine().ProcessOperations(GetDAG().ComputeLikelihoods());
   auto likelihoods = GetGPEngine().GetPerGPCSPLogLikelihoods();
+  std::cout << "GPEngine::UpdateEngineAfterModifying [END]" << std::endl;
```
Comment (chrisjenningsshaffer) [inline src/nni_evaluation_engine.cpp:144]: Let's either remove the printed message or make it optional with an is_quiet parameter.

File: src/tp_engine.hpp [hunk 3]
```diff
@@ -362,17 +337,29 @@ class TPEngine {
...
+
+  // ** Evaluation Engine - Likelihood
+
+  // EigenConstMatrixXdRef GetLikelihoodMatrix() {
+  //   Assert(HasLikelihoodEvalEngine(), "Must MakeLikelihoodEvalEngine before
+  //   access."); auto &log_likelihoods =
+  //       GetLikelihoodEvalEngine().GetDAGBranchHandler().GetBranchLengthData();
+  //   return log_likelihoods.block(0, 0, GetEdgeCount(), log_likelihoods.cols());
+  // }
+  const PLVEdgeHandler &GetLikelihoodPVs() const {
```
Comment (chrisjenningsshaffer) [inline src/tp_engine.hpp:349]: Commented code can go?

File: src/pybito.cpp [hunk 4]
```diff
@@ -824,8 +824,9 @@ PYBIND11_MODULE(bito, m) {
           "Add parent/child subsplit pair to DAG.")
       .def("add_nodes", &GPDAG::AddNodes)
       .def("add_edges", &GPDAG::AddEdges)
-      .def("fully_connect", &GPDAG::FullyConnect,
-           "Adds all valid edges with present nodes to the DAG.")
+      .def(
+          "fully_connect", [](GPDAG &self) { self.FullyConnect(); },
+          "Adds all valid edges with present nodes to the DAG.")
       // ** I/O
```
Comment (chrisjenningsshaffer) [inline src/pybito.cpp:830]: Python complains with this version because it doesn't know about the return type. I've removed the return value, since we don't need it on the python side and that's less work than exposing it here.

**Review by chrisjenningsshaffer — CHANGES_REQUESTED** [review]
Minor stuff only.

File: src/tp_engine.hpp (hunk 3 above)
Comment (davidrich27) [reply src/tp_engine.hpp:325]: Removed.

File: src/nni_evaluation_engine.cpp (hunk 1 above)
Comment (davidrich27) [reply src/nni_evaluation_engine.cpp]: Removed.

File: src/tp_engine.hpp (hunk 3 above)
Comment (davidrich27) [reply src/tp_engine.hpp:325]: Removed.

File: src/pybito.cpp (hunk 4 above)
Comment (davidrich27) [reply src/pybito.cpp:830]: It looks like you made these changes.

**Review by chrisjenningsshaffer — APPROVED** [review]
